[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/deoplete-rct'
depends = ['deoplete.nvim']
on_ft = 'ruby'
hook_source = '''
let g:deoplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
depends = ['deoplete.nvim']
on_ft = 'python'
hook_source = 'source ~/.vim/rc/plugins/jedi.vim'

[[plugins]]
repo = 'nvie/vim-flake8'
if = 'executable("flake8")'
on_ft = 'python'
