[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
hook_source = 'source ~/.vim/rc/plugins/deoplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = 'python'

[[plugins]]
repo = 'nvie/vim-flake8'
if = 'executable("flake8")'
on_ft = 'python'
